apiVersion: v1
kind: Secret
metadata:
  name: aws-odh-bucket
  annotations:
     serving.kserve.io/s3-endpoint: s3.us-east.cloud-object-storage.appdomain.cloud # replace with your s3 endpoint e.g minio-service.kubeflow:9000
     serving.kserve.io/s3-usehttps: "1" # by default 1, if testing with minio you can set to 0
     serving.kserve.io/s3-region: "us-east"
     serving.kserve.io/s3-useanoncredential: "false" # omitting this is the same as false, if true will ignore provided credential and use anonymous credentials
type: Opaque
stringData: # use `stringData` for raw credential string or `data` for base64 encoded string
  AWS_ACCESS_KEY_ID: ACCESS_ID
  AWS_SECRET_ACCESS_KEY: SECRET_KEY
